// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_core_volume

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CoreVolumeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"attachments": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"device": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"instance_id": schema.Int64Attribute{
							Computed: true,
						},
						"protected": schema.BoolAttribute{
							Computed: true,
						},
						"status": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: AttachmentsType{
						ObjectType: types.ObjectType{
							AttrTypes: AttachmentsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"bootable": schema.BoolAttribute{
				Computed: true,
			},
			"callback_url": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A URL that can be attached to the volume you are creating. This `callback_url` will post any action events that occur to your volume to the provided URL.",
				MarkdownDescription: "A URL that can be attached to the volume you are creating. This `callback_url` will post any action events that occur to your volume to the provided URL.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtMost(250),
				},
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A brief description or comment about the volume.",
				MarkdownDescription: "A brief description or comment about the volume.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"environment": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"features": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{},
						CustomType: FeaturesType{
							ObjectType: types.ObjectType{
								AttrTypes: FeaturesValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
					"region": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: EnvironmentType{
					ObjectType: types.ObjectType{
						AttrTypes: EnvironmentValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"environment_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the [environment](https://docs.hyperstack.cloud/docs/api-reference/core-resources/environments/) within which the volume is being created.",
				MarkdownDescription: "The name of the [environment](https://docs.hyperstack.cloud/docs/api-reference/core-resources/environments/) within which the volume is being created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"image_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the operating system image that will be associated with the volume. By providing an `image_id` in the create volume request, you will create a bootable volume.",
				MarkdownDescription: "The ID of the operating system image that will be associated with the volume. By providing an `image_id` in the create volume request, you will create a bootable volume.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the volume being created.",
				MarkdownDescription: "The name of the volume being created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthAtMost(50),
				},
			},
			"os_image": schema.StringAttribute{
				Computed: true,
			},
			"size": schema.Int64Attribute{
				Required:            true,
				Description:         "The size of the volume in GB. 1048576GB storage capacity per volume.",
				MarkdownDescription: "The size of the volume in GB. 1048576GB storage capacity per volume.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"volume_type": schema.StringAttribute{
				Required:            true,
				Description:         "Specifies the type of volume being created, which determines the storage technology it will use. Call the [List volume types](https://infrahub-api-doc.nexgencloud.com/#get-/core/volumes) endpoint to retrieve a list of available volume model types.",
				MarkdownDescription: "Specifies the type of volume being created, which determines the storage technology it will use. Call the [List volume types](https://infrahub-api-doc.nexgencloud.com/#get-/core/volumes) endpoint to retrieve a list of available volume model types.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

type CoreVolumeModel struct {
	Attachments     types.List       `tfsdk:"attachments"`
	Bootable        types.Bool       `tfsdk:"bootable"`
	CallbackUrl     types.String     `tfsdk:"callback_url"`
	CreatedAt       types.String     `tfsdk:"created_at"`
	Description     types.String     `tfsdk:"description"`
	Environment     EnvironmentValue `tfsdk:"environment"`
	EnvironmentName types.String     `tfsdk:"environment_name"`
	Id              types.Int64      `tfsdk:"id"`
	ImageId         types.Int64      `tfsdk:"image_id"`
	Name            types.String     `tfsdk:"name"`
	OsImage         types.String     `tfsdk:"os_image"`
	Size            types.Int64      `tfsdk:"size"`
	Status          types.String     `tfsdk:"status"`
	UpdatedAt       types.String     `tfsdk:"updated_at"`
	VolumeType      types.String     `tfsdk:"volume_type"`
}

var _ basetypes.ObjectTypable = AttachmentsType{}

type AttachmentsType struct {
	basetypes.ObjectType
}

func (t AttachmentsType) Equal(o attr.Type) bool {
	other, ok := o.(AttachmentsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AttachmentsType) String() string {
	return "AttachmentsType"
}

func (t AttachmentsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	deviceAttribute, ok := attributes["device"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device is missing from object`)

		return nil, diags
	}

	deviceVal, ok := deviceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device expected to be basetypes.StringValue, was: %T`, deviceAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	instanceIdAttribute, ok := attributes["instance_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance_id is missing from object`)

		return nil, diags
	}

	instanceIdVal, ok := instanceIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance_id expected to be basetypes.Int64Value, was: %T`, instanceIdAttribute))
	}

	protectedAttribute, ok := attributes["protected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protected is missing from object`)

		return nil, diags
	}

	protectedVal, ok := protectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protected expected to be basetypes.BoolValue, was: %T`, protectedAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AttachmentsValue{
		Device:     deviceVal,
		Id:         idVal,
		InstanceId: instanceIdVal,
		Protected:  protectedVal,
		Status:     statusVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAttachmentsValueNull() AttachmentsValue {
	return AttachmentsValue{
		state: attr.ValueStateNull,
	}
}

func NewAttachmentsValueUnknown() AttachmentsValue {
	return AttachmentsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAttachmentsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AttachmentsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AttachmentsValue Attribute Value",
				"While creating a AttachmentsValue value, a missing attribute value was detected. "+
					"A AttachmentsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttachmentsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AttachmentsValue Attribute Type",
				"While creating a AttachmentsValue value, an invalid attribute value was detected. "+
					"A AttachmentsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttachmentsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AttachmentsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AttachmentsValue Attribute Value",
				"While creating a AttachmentsValue value, an extra attribute value was detected. "+
					"A AttachmentsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AttachmentsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAttachmentsValueUnknown(), diags
	}

	deviceAttribute, ok := attributes["device"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`device is missing from object`)

		return NewAttachmentsValueUnknown(), diags
	}

	deviceVal, ok := deviceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`device expected to be basetypes.StringValue, was: %T`, deviceAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewAttachmentsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	instanceIdAttribute, ok := attributes["instance_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance_id is missing from object`)

		return NewAttachmentsValueUnknown(), diags
	}

	instanceIdVal, ok := instanceIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance_id expected to be basetypes.Int64Value, was: %T`, instanceIdAttribute))
	}

	protectedAttribute, ok := attributes["protected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`protected is missing from object`)

		return NewAttachmentsValueUnknown(), diags
	}

	protectedVal, ok := protectedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`protected expected to be basetypes.BoolValue, was: %T`, protectedAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewAttachmentsValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewAttachmentsValueUnknown(), diags
	}

	return AttachmentsValue{
		Device:     deviceVal,
		Id:         idVal,
		InstanceId: instanceIdVal,
		Protected:  protectedVal,
		Status:     statusVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAttachmentsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AttachmentsValue {
	object, diags := NewAttachmentsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAttachmentsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AttachmentsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAttachmentsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAttachmentsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAttachmentsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAttachmentsValueMust(AttachmentsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AttachmentsType) ValueType(ctx context.Context) attr.Value {
	return AttachmentsValue{}
}

var _ basetypes.ObjectValuable = AttachmentsValue{}

type AttachmentsValue struct {
	Device     basetypes.StringValue `tfsdk:"device"`
	Id         basetypes.Int64Value  `tfsdk:"id"`
	InstanceId basetypes.Int64Value  `tfsdk:"instance_id"`
	Protected  basetypes.BoolValue   `tfsdk:"protected"`
	Status     basetypes.StringValue `tfsdk:"status"`
	state      attr.ValueState
}

func (v AttachmentsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["device"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["instance_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["protected"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Device.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["device"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.InstanceId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["instance_id"] = val

		val, err = v.Protected.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["protected"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AttachmentsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AttachmentsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AttachmentsValue) String() string {
	return "AttachmentsValue"
}

func (v AttachmentsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"device":      basetypes.StringType{},
		"id":          basetypes.Int64Type{},
		"instance_id": basetypes.Int64Type{},
		"protected":   basetypes.BoolType{},
		"status":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"device":      v.Device,
			"id":          v.Id,
			"instance_id": v.InstanceId,
			"protected":   v.Protected,
			"status":      v.Status,
		})

	return objVal, diags
}

func (v AttachmentsValue) Equal(o attr.Value) bool {
	other, ok := o.(AttachmentsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Device.Equal(other.Device) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.InstanceId.Equal(other.InstanceId) {
		return false
	}

	if !v.Protected.Equal(other.Protected) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v AttachmentsValue) Type(ctx context.Context) attr.Type {
	return AttachmentsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AttachmentsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"device":      basetypes.StringType{},
		"id":          basetypes.Int64Type{},
		"instance_id": basetypes.Int64Type{},
		"protected":   basetypes.BoolType{},
		"status":      basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = EnvironmentType{}

type EnvironmentType struct {
	basetypes.ObjectType
}

func (t EnvironmentType) Equal(o attr.Type) bool {
	other, ok := o.(EnvironmentType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EnvironmentType) String() string {
	return "EnvironmentType"
}

func (t EnvironmentType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	featuresAttribute, ok := attributes["features"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`features is missing from object`)

		return nil, diags
	}

	featuresVal, ok := featuresAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`features expected to be basetypes.ObjectValue, was: %T`, featuresAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return nil, diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EnvironmentValue{
		Features: featuresVal,
		Name:     nameVal,
		Region:   regionVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewEnvironmentValueNull() EnvironmentValue {
	return EnvironmentValue{
		state: attr.ValueStateNull,
	}
}

func NewEnvironmentValueUnknown() EnvironmentValue {
	return EnvironmentValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEnvironmentValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EnvironmentValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EnvironmentValue Attribute Value",
				"While creating a EnvironmentValue value, a missing attribute value was detected. "+
					"A EnvironmentValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnvironmentValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EnvironmentValue Attribute Type",
				"While creating a EnvironmentValue value, an invalid attribute value was detected. "+
					"A EnvironmentValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnvironmentValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EnvironmentValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EnvironmentValue Attribute Value",
				"While creating a EnvironmentValue value, an extra attribute value was detected. "+
					"A EnvironmentValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EnvironmentValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEnvironmentValueUnknown(), diags
	}

	featuresAttribute, ok := attributes["features"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`features is missing from object`)

		return NewEnvironmentValueUnknown(), diags
	}

	featuresVal, ok := featuresAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`features expected to be basetypes.ObjectValue, was: %T`, featuresAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewEnvironmentValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return NewEnvironmentValueUnknown(), diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	if diags.HasError() {
		return NewEnvironmentValueUnknown(), diags
	}

	return EnvironmentValue{
		Features: featuresVal,
		Name:     nameVal,
		Region:   regionVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewEnvironmentValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EnvironmentValue {
	object, diags := NewEnvironmentValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEnvironmentValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EnvironmentType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEnvironmentValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEnvironmentValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEnvironmentValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEnvironmentValueMust(EnvironmentValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EnvironmentType) ValueType(ctx context.Context) attr.Value {
	return EnvironmentValue{}
}

var _ basetypes.ObjectValuable = EnvironmentValue{}

type EnvironmentValue struct {
	Features basetypes.ObjectValue `tfsdk:"features"`
	Name     basetypes.StringValue `tfsdk:"name"`
	Region   basetypes.StringValue `tfsdk:"region"`
	state    attr.ValueState
}

func (v EnvironmentValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["features"] = basetypes.ObjectType{
		AttrTypes: FeaturesValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Features.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["features"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Region.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EnvironmentValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EnvironmentValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EnvironmentValue) String() string {
	return "EnvironmentValue"
}

func (v EnvironmentValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var features basetypes.ObjectValue

	if v.Features.IsNull() {
		features = types.ObjectNull(
			FeaturesValue{}.AttributeTypes(ctx),
		)
	}

	if v.Features.IsUnknown() {
		features = types.ObjectUnknown(
			FeaturesValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Features.IsNull() && !v.Features.IsUnknown() {
		features = types.ObjectValueMust(
			FeaturesValue{}.AttributeTypes(ctx),
			v.Features.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"features": basetypes.ObjectType{
			AttrTypes: FeaturesValue{}.AttributeTypes(ctx),
		},
		"name":   basetypes.StringType{},
		"region": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"features": features,
			"name":     v.Name,
			"region":   v.Region,
		})

	return objVal, diags
}

func (v EnvironmentValue) Equal(o attr.Value) bool {
	other, ok := o.(EnvironmentValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Features.Equal(other.Features) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Region.Equal(other.Region) {
		return false
	}

	return true
}

func (v EnvironmentValue) Type(ctx context.Context) attr.Type {
	return EnvironmentType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EnvironmentValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"features": basetypes.ObjectType{
			AttrTypes: FeaturesValue{}.AttributeTypes(ctx),
		},
		"name":   basetypes.StringType{},
		"region": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = FeaturesType{}

type FeaturesType struct {
	basetypes.ObjectType
}

func (t FeaturesType) Equal(o attr.Type) bool {
	other, ok := o.(FeaturesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t FeaturesType) String() string {
	return "FeaturesType"
}

func (t FeaturesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return FeaturesValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewFeaturesValueNull() FeaturesValue {
	return FeaturesValue{
		state: attr.ValueStateNull,
	}
}

func NewFeaturesValueUnknown() FeaturesValue {
	return FeaturesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewFeaturesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (FeaturesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing FeaturesValue Attribute Value",
				"While creating a FeaturesValue value, a missing attribute value was detected. "+
					"A FeaturesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FeaturesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid FeaturesValue Attribute Type",
				"While creating a FeaturesValue value, an invalid attribute value was detected. "+
					"A FeaturesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FeaturesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("FeaturesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra FeaturesValue Attribute Value",
				"While creating a FeaturesValue value, an extra attribute value was detected. "+
					"A FeaturesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra FeaturesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewFeaturesValueUnknown(), diags
	}

	if diags.HasError() {
		return NewFeaturesValueUnknown(), diags
	}

	return FeaturesValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewFeaturesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) FeaturesValue {
	object, diags := NewFeaturesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewFeaturesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t FeaturesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewFeaturesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewFeaturesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewFeaturesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewFeaturesValueMust(FeaturesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t FeaturesType) ValueType(ctx context.Context) attr.Value {
	return FeaturesValue{}
}

var _ basetypes.ObjectValuable = FeaturesValue{}

type FeaturesValue struct {
	state attr.ValueState
}

func (v FeaturesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v FeaturesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v FeaturesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v FeaturesValue) String() string {
	return "FeaturesValue"
}

func (v FeaturesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v FeaturesValue) Equal(o attr.Value) bool {
	other, ok := o.(FeaturesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v FeaturesValue) Type(ctx context.Context) attr.Type {
	return FeaturesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v FeaturesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
