version: '3'

silent: true

vars:
  NAME: "terraform-provider-hyperstack"
  DIR_DATA: "{{.ROOT_DIR}}/data"
  DIR_EXAMPLES: "{{.ROOT_DIR}}/examples"
  DIR_TESTS: "{{.ROOT_DIR}}/tests"
  DIR_ARTIFACTS: "{{.ROOT_DIR}}/artifacts"
  DIR_BINPROVIDER: "{{.DIR_ARTIFACTS}}/provider"
  DIR_PROVIDER: "{{.ROOT_DIR}}/internal/provider"
  DIR_GENPROVIDER: "{{.ROOT_DIR}}/internal/genprovider"
  API_SPEC_PATH: "{{.DIR_ARTIFACTS}}/api.json"
  PROVIDER_SPEC_PATH: "{{.DIR_ARTIFACTS}}/provider-spec.json"

  ARCH:
    # language=bash
    sh: echo "$(go env GOOS)_$(go env GOARCH)"

  TF_PROVIDER_VERSION: "0.1.0"
  TF_PROVIDER_NAME: "hyperstack"
  TF_PROVIDER_PATH: |-
    registry.terraform.io/nexgencloud/{{.TF_PROVIDER_NAME}}/{{.TF_PROVIDER_VERSION}}/{{.ARCH}}
  TF_PROVIDER_DIR: "{{.DIR_BINPROVIDER}}/{{.TF_PROVIDER_PATH}}"
  TF_PROVIDER_BINARY: "{{.TF_PROVIDER_DIR}}/{{.NAME}}_v{{.TF_PROVIDER_VERSION}}"

env:
  TF_CLI_CONFIG_FILE: "{{.DIR_TESTS}}/dev.tfrc"
  HYPERSTACK_STAGING: "true"
  HYPERSTACK_API_KEY: ~
  TF_CLOUD_TOKEN: ~
  TF_CLOUD_KEY_ID: ~
  TF_CLOUD_ORG: nexgencloud


tasks:
  init:
    desc: |
      Install all the necessary dependencies
    cmds:
      # language=bash
      - |
        # TODO: check go.mod
        go install
        go install github.com/hashicorp/terraform-plugin-codegen-openapi/cmd/tfplugingen-openapi@latest
        go install github.com/hashicorp/terraform-plugin-codegen-framework/cmd/tfplugingen-framework@latest

  update:
    desc: |
      Updates dependencies
    cmds:
      # language=bash
      - |
        go mod tidy

  build:
    desc: |
      Builds the provider
    cmds:
      # language=bash
      - |
        if [[ "$(go env GOOS)" != "darwin" ]]; then
          # https://github.com/aws/aws-lambda-go/issues/340#issue-748665352
          # https://github.com/hashicorp/terraform/blob/main/BUILDING.md#cgo_enabled
          export CGO_ENABLED=0
        fi
        mkdir -p "{{.TF_PROVIDER_DIR}}"
        go build -o "{{.TF_PROVIDER_BINARY}}"
  gen:
    desc: |
      Generates schemas
    cmds:
      - task: build-api-spec
      - task: build-provider-spec

  test-unit:
    desc: |
      Tests the provider
    dotenv: ['.env']
    cmds:
      - task: build
      # language=bash
      - |
        TF_ACC=1 go test ./... -v -timeout 120m

  provider-create:
    desc: |
      Creates provider in terraform cloud
    dotenv: ['.env']
    cmds:
      # https://developer.hashicorp.com/terraform/cloud-docs/registry/publish-providers
      # language=bash
      - |
        curl \
          --header "Authorization: Bearer ${TF_CLOUD_TOKEN}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @provider.json \
          https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORG}/registry-providers
        curl \
          --header "Authorization: Bearer ${TF_CLOUD_TOKEN}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data @key.json \
          https://app.terraform.io/api/registry/private/v2/gpg-keys

  provider-publish:
    desc: |
      Publishes new provider version
    dotenv: ['../../.env']
    dir: "{{.DIR_BINPROVIDER}}"
    vars:
      BIN_NAME: "{{.NAME}}_v{{.TF_PROVIDER_VERSION}}"
      ZIP_NAME: "{{.BIN_NAME}}_{{.ARCH}}.zip"
      SHA_NAME: "{{.BIN_NAME}}_SHA256SUMS"
      PLATFORM_JSON: "{{.DIR_BINPROVIDER}}/platform.json"
      VERSION_JSON: "{{.DIR_BINPROVIDER}}/version.json"
    cmds:
      - task: build
      # https://developer.hashicorp.com/terraform/registry/providers/publishing#manually-preparing-a-release
      # language=bash
      - echo "Uploading provider {{.NAME}} version v{{.TF_PROVIDER_VERSION}}:"
      # language=bash
      - |
        echo -n "- deleting existing release... "
        rm -f \
          "{{.BIN_NAME}}" \
          "{{.SHA_NAME}}" \
          "{{.SHA_NAME}}.sig"
        curl -s \
          --header "Authorization: Bearer ${TF_CLOUD_TOKEN}" \
          --header "Content-Type: application/vnd.api+json" \
          --request DELETE \
          https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORG}/registry-providers/private/${TF_CLOUD_ORG}/{{.TF_PROVIDER_NAME}}/versions/{{.TF_PROVIDER_VERSION}} \
            > /dev/null
        echo "done"
      # language=bash
      - |
        echo -n "- creating and signing archive... "
        cp "{{.NAME}}" "{{.BIN_NAME}}"
        zip -q "{{.ZIP_NAME}}" "{{.BIN_NAME}}"
        shasum -a 256 "{{.ZIP_NAME}}" > "{{.SHA_NAME}}"
        gpg \
          --output "{{.SHA_NAME}}.sig" \
          --detach-sign "{{.SHA_NAME}}"
        echo "done"
      # language=bash
      - |
        echo -n "- creating a new cloud release... "
        cat <<EOF > "{{.VERSION_JSON}}"
        {
          "data": {
            "type": "registry-provider-versions",
            "attributes": {
              "version": "{{.TF_PROVIDER_VERSION}}",
              "key-id": "${TF_CLOUD_KEY_ID}",
              "protocols": ["5.0"]
            }
          }
        }
        EOF
        curl -s \
          --header "Authorization: Bearer ${TF_CLOUD_TOKEN}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data "@{{.VERSION_JSON}}" \
          https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORG}/registry-providers/private/${TF_CLOUD_ORG}/{{.TF_PROVIDER_NAME}}/versions \
            > "{{.DIR_BINPROVIDER}}/create_result.json"
        echo "done"
      # language=bash
      - |
        echo -n "- uploading SHA256SUMS... "
        curl -s \
          -T \
          "{{.SHA_NAME}}" \
          "$(cat "{{.DIR_BINPROVIDER}}/create_result.json" | jq -r '.data.links."shasums-upload"')"
        echo "done"
      # language=bash
      - |
        echo -n "- uploading SHA256SUMS.sig... "
        curl -s \
          -T \
          "{{.SHA_NAME}}.sig" \
          "$(cat "{{.DIR_BINPROVIDER}}/create_result.json" | jq -r '.data.links."shasums-sig-upload"')"
        echo "done"
      # language=bash
      - |
        echo -n "- uploading release... "
        cat <<EOF > "{{.PLATFORM_JSON}}"
        {
          "data": {
            "type": "registry-provider-version-platforms",
            "attributes": {
              "os": "$(go env GOOS)",
              "arch": "$(go env GOARCH)",
              "shasum": "$(shasum -a 256 "{{.ZIP_NAME}}" | cut -d' ' -f1)",
              "filename": "{{.ZIP_NAME}}"
            }
          }
        }
        EOF
        curl -s \
          --header "Authorization: Bearer ${TF_CLOUD_TOKEN}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data "@{{.PLATFORM_JSON}}" \
          https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORG}/registry-providers/private/${TF_CLOUD_ORG}/{{.TF_PROVIDER_NAME}}/versions/{{.TF_PROVIDER_VERSION}}/platforms \
            > "{{.DIR_BINPROVIDER}}/publish_result.json"
        curl -s \
          -T \
          "{{.ZIP_NAME}}" \
          "$(cat "{{.DIR_BINPROVIDER}}/publish_result.json" | jq -r '.data.links."provider-binary-upload"')"
        echo "done"
      # language=bash
      - |
        cat <<EOF
        Release is ready v{{.TF_PROVIDER_VERSION}}:

        terraform {
          required_providers {
            hyperstack = {
              source = "app.terraform.io/${TF_CLOUD_ORG}/{{.TF_PROVIDER_NAME}}"
              version = "{{.TF_PROVIDER_VERSION}}"
            }
          }
        }
        EOF

  test:
    desc: |
      Tests the provider
    dotenv: ['.env']
    vars:
      RUN_INIT: true
      RUN_CREATE_PLAN: true
      RUN_CREATE_APPLY: true
      RUN_DESTROY_PLAN: true
      RUN_DESTROY_APPLY: true
      TF_TESTS: |-
        auth_me
        auth_organization
        auth_roles
        core_environments
        core_images
        core_regions
        core_gpus
        core_flavors
        core_keypairs
        core_vms
        core_vm
    cmds:
      - task: build
      # language=bash
      - |
        # https://developer.hashicorp.com/terraform/cli/config/environment-variables
        export TF_LOG=DEBUG
        for module in {{join " " (splitArgs .TF_TESTS)}}; do
          ARTIFACTS_DIR="{{.DIR_ARTIFACTS}}/tests/${module}"
          MODULE_DIR="{{.DIR_TESTS}}/${module}"
          cd "${MODULE_DIR}"

          mkdir -p "${ARTIFACTS_DIR}/files"
          export TF_DATA_DIR="${ARTIFACTS_DIR}/.terraform"
          export TF_VAR_artifacts_directory="${ARTIFACTS_DIR}/files"
          
          # https://developer.hashicorp.com/terraform/language/settings/backends/configuration#file
          # https://developer.hashicorp.com/terraform/language/settings/backends/configuration
          # https://developer.hashicorp.com/terraform/language/settings/backends/local
          BACKEND_FILE="${ARTIFACTS_DIR}/backend.tfvars"
          echo "path=\"${ARTIFACTS_DIR}/terraform.tfstate\"" > "${BACKEND_FILE}"
          
          if [[ "{{.RUN_INIT}}" == "true" ]]; then
            # Remove lock file due to possible checksum change
            rm -f "${MODULE_DIR}/.terraform.lock.hcl"
            # TODO: store output and show only on error
            TF_LOG_PATH="${ARTIFACTS_DIR}/tf_init.log" \
              terraform init -input=false -backend-config="${BACKEND_FILE}" > /dev/null
          fi
          
          TFPLAN="${ARTIFACTS_DIR}/tfplan"
          [[ "{{.RUN_CREATE_PLAN}}" == "true" ]] && \
            TF_LOG_PATH="${ARTIFACTS_DIR}/tf_create_plan.log" \
            terraform plan -out "${TFPLAN}"
          [[ "{{.RUN_CREATE_APPLY}}" == "true" ]] && \
            TF_LOG_PATH="${ARTIFACTS_DIR}/tf_create_apply.log" \
            terraform apply "${TFPLAN}"
          [[ "{{.RUN_DESTROY_PLAN}}" == "true" ]] && \
            TF_LOG_PATH="${ARTIFACTS_DIR}/tf_destroy_plan.log" \
            terraform plan -out "${TFPLAN}" -destroy
          [[ "{{.RUN_DESTROY_APPLY}}" == "true" ]] && \
            TF_LOG_PATH="${ARTIFACTS_DIR}/tf_destroy_apply.log" \
            terraform apply "${TFPLAN}"
          cd - > /dev/null
        done

  debug-me:
    desc: |
      Checks API token
    dotenv: ['.env']
    cmds:
      # language=bash
      - |
        curl -X GET "https://infrahub-api-stg.ngbackend.cloud/v1/core/flavors" \
          -H "accept: application/json" \
          -H "api_key: ${HYPERSTACK_API_KEY}"

  build-api-spec:
    desc: |
      Pulls the latest api.json from the server
    vars:
      SPEC_PATH: |-
        https://infrahub-api-doc.nexgencloud.com/api.json
      SCRIPTS_DIR: "scripts"
      FIX_API_SPEC: "{{.SCRIPTS_DIR}}/fix_api_spec.py"
    cmds:
      # language=bash
      - |
        echo "Pulling the latest swagger spec and generating Go SDK..."
        curl "{{.SPEC_PATH}}"  | \
          python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.stdin.read()))" \
            > "{{.API_SPEC_PATH}}"
        python3 "{{.FIX_API_SPEC}}" "{{.API_SPEC_PATH}}"

  build-provider-spec:
    desc: |
      Gen schemas
    vars:
      TF_DATA_SOURCES:
        # language=bash
        sh: cat "{{.DIR_DATA}}/generator-config.yml" | yq e -o=c ".data_sources | keys | .[]"
      SCRIPTS_DIR: "scripts"
      FIX_PROVIDER_SPEC: "{{.SCRIPTS_DIR}}/fix_provider_spec.py"
    cmds:
      # language=bash
      - |
        tfplugingen-openapi generate \
          --config "{{.DIR_DATA}}/generator-config.yml" \
          --output "{{.PROVIDER_SPEC_PATH}}" \
          "{{.API_SPEC_PATH}}"
        python3 "{{.FIX_PROVIDER_SPEC}}" "{{.PROVIDER_SPEC_PATH}}"
      # language=bash
      - |
        rm -Rf "{{.DIR_GENPROVIDER}}"
        mkdir -p "{{.DIR_GENPROVIDER}}"
        tfplugingen-framework generate data-sources \
          --input "{{.DIR_ARTIFACTS}}/provider-spec.json" \
          --output "{{.DIR_GENPROVIDER}}"
        tfplugingen-framework generate resources \
          --input "{{.DIR_ARTIFACTS}}/provider-spec.json" \
          --output "{{.DIR_GENPROVIDER}}"
      # language=bash
      - |
        rm -Rf "{{.DIR_PROVIDER}}/data_source"
        mkdir -p "{{.DIR_PROVIDER}}/data_source"
        for row in {{join " " (splitArgs .TF_DATA_SOURCES)}}; do
          tfplugingen-framework scaffold data-source \
            --name "${row}" \
            --force \
            --output-dir "{{.DIR_PROVIDER}}/data_source"
        done
