// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_core_keypair

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CoreKeypairDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"environment": schema.StringAttribute{
				Computed: true,
			},
			"fingerprint": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"public_key": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type CoreKeypairModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	Environment types.String `tfsdk:"environment"`
	Fingerprint types.String `tfsdk:"fingerprint"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	PublicKey   types.String `tfsdk:"public_key"`
}
