// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_core_keypairs

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CoreKeypairsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"core_keypairs": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"environment": schema.StringAttribute{
							Computed: true,
						},
						"fingerprint": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"public_key": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: CoreKeypairsType{
						ObjectType: types.ObjectType{
							AttrTypes: CoreKeypairsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type CoreKeypairsModel struct {
	CoreKeypairs types.Set `tfsdk:"core_keypairs"`
}

var _ basetypes.ObjectTypable = CoreKeypairsType{}

type CoreKeypairsType struct {
	basetypes.ObjectType
}

func (t CoreKeypairsType) Equal(o attr.Type) bool {
	other, ok := o.(CoreKeypairsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CoreKeypairsType) String() string {
	return "CoreKeypairsType"
}

func (t CoreKeypairsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	environmentAttribute, ok := attributes["environment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`environment is missing from object`)

		return nil, diags
	}

	environmentVal, ok := environmentAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`environment expected to be basetypes.StringValue, was: %T`, environmentAttribute))
	}

	fingerprintAttribute, ok := attributes["fingerprint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fingerprint is missing from object`)

		return nil, diags
	}

	fingerprintVal, ok := fingerprintAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fingerprint expected to be basetypes.StringValue, was: %T`, fingerprintAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	publicKeyAttribute, ok := attributes["public_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public_key is missing from object`)

		return nil, diags
	}

	publicKeyVal, ok := publicKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public_key expected to be basetypes.StringValue, was: %T`, publicKeyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CoreKeypairsValue{
		CreatedAt:   createdAtVal,
		Environment: environmentVal,
		Fingerprint: fingerprintVal,
		Id:          idVal,
		Name:        nameVal,
		PublicKey:   publicKeyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewCoreKeypairsValueNull() CoreKeypairsValue {
	return CoreKeypairsValue{
		state: attr.ValueStateNull,
	}
}

func NewCoreKeypairsValueUnknown() CoreKeypairsValue {
	return CoreKeypairsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCoreKeypairsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CoreKeypairsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CoreKeypairsValue Attribute Value",
				"While creating a CoreKeypairsValue value, a missing attribute value was detected. "+
					"A CoreKeypairsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CoreKeypairsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CoreKeypairsValue Attribute Type",
				"While creating a CoreKeypairsValue value, an invalid attribute value was detected. "+
					"A CoreKeypairsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CoreKeypairsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CoreKeypairsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CoreKeypairsValue Attribute Value",
				"While creating a CoreKeypairsValue value, an extra attribute value was detected. "+
					"A CoreKeypairsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CoreKeypairsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCoreKeypairsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	environmentAttribute, ok := attributes["environment"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`environment is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	environmentVal, ok := environmentAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`environment expected to be basetypes.StringValue, was: %T`, environmentAttribute))
	}

	fingerprintAttribute, ok := attributes["fingerprint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fingerprint is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	fingerprintVal, ok := fingerprintAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fingerprint expected to be basetypes.StringValue, was: %T`, fingerprintAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	publicKeyAttribute, ok := attributes["public_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public_key is missing from object`)

		return NewCoreKeypairsValueUnknown(), diags
	}

	publicKeyVal, ok := publicKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public_key expected to be basetypes.StringValue, was: %T`, publicKeyAttribute))
	}

	if diags.HasError() {
		return NewCoreKeypairsValueUnknown(), diags
	}

	return CoreKeypairsValue{
		CreatedAt:   createdAtVal,
		Environment: environmentVal,
		Fingerprint: fingerprintVal,
		Id:          idVal,
		Name:        nameVal,
		PublicKey:   publicKeyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewCoreKeypairsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CoreKeypairsValue {
	object, diags := NewCoreKeypairsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCoreKeypairsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CoreKeypairsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCoreKeypairsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCoreKeypairsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCoreKeypairsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCoreKeypairsValueMust(CoreKeypairsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CoreKeypairsType) ValueType(ctx context.Context) attr.Value {
	return CoreKeypairsValue{}
}

var _ basetypes.ObjectValuable = CoreKeypairsValue{}

type CoreKeypairsValue struct {
	CreatedAt   basetypes.StringValue `tfsdk:"created_at"`
	Environment basetypes.StringValue `tfsdk:"environment"`
	Fingerprint basetypes.StringValue `tfsdk:"fingerprint"`
	Id          basetypes.Int64Value  `tfsdk:"id"`
	Name        basetypes.StringValue `tfsdk:"name"`
	PublicKey   basetypes.StringValue `tfsdk:"public_key"`
	state       attr.ValueState
}

func (v CoreKeypairsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["environment"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fingerprint"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["public_key"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Environment.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["environment"] = val

		val, err = v.Fingerprint.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fingerprint"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.PublicKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["public_key"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CoreKeypairsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CoreKeypairsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CoreKeypairsValue) String() string {
	return "CoreKeypairsValue"
}

func (v CoreKeypairsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"created_at":  basetypes.StringType{},
			"environment": basetypes.StringType{},
			"fingerprint": basetypes.StringType{},
			"id":          basetypes.Int64Type{},
			"name":        basetypes.StringType{},
			"public_key":  basetypes.StringType{},
		},
		map[string]attr.Value{
			"created_at":  v.CreatedAt,
			"environment": v.Environment,
			"fingerprint": v.Fingerprint,
			"id":          v.Id,
			"name":        v.Name,
			"public_key":  v.PublicKey,
		})

	return objVal, diags
}

func (v CoreKeypairsValue) Equal(o attr.Value) bool {
	other, ok := o.(CoreKeypairsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Environment.Equal(other.Environment) {
		return false
	}

	if !v.Fingerprint.Equal(other.Fingerprint) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.PublicKey.Equal(other.PublicKey) {
		return false
	}

	return true
}

func (v CoreKeypairsValue) Type(ctx context.Context) attr.Type {
	return CoreKeypairsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CoreKeypairsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"environment": basetypes.StringType{},
		"fingerprint": basetypes.StringType{},
		"id":          basetypes.Int64Type{},
		"name":        basetypes.StringType{},
		"public_key":  basetypes.StringType{},
	}
}
