name: test
run-name: ${{ github.actor }} foobar
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/taskfile
        with:
          who-to-greet: 'Mona the Octocat'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v