// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_core_cluster_node

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CoreClusterNodeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"count": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"message": schema.StringAttribute{
				Computed: true,
			},
			"node_group": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"nodes": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"instance": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"contract_id": schema.Int64Attribute{
									Computed: true,
								},
								"fixed_ip": schema.StringAttribute{
									Computed: true,
								},
								"floating_ip": schema.StringAttribute{
									Computed: true,
								},
								"floating_ip_status": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.Int64Attribute{
									Computed: true,
								},
								"image_id": schema.Int64Attribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
								"status": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: InstanceType{
								ObjectType: types.ObjectType{
									AttrTypes: InstanceValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"is_bastion": schema.BoolAttribute{
							Computed: true,
						},
						"node_group_id": schema.Int64Attribute{
							Computed: true,
						},
						"node_group_name": schema.StringAttribute{
							Computed: true,
						},
						"requires_public_ip": schema.BoolAttribute{
							Computed: true,
						},
						"role": schema.StringAttribute{
							Computed: true,
						},
						"status": schema.StringAttribute{
							Computed: true,
						},
						"status_reason": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: NodesType{
						ObjectType: types.ObjectType{
							AttrTypes: NodesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"role": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"worker",
						"master",
					),
				},
			},
			"status": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

type CoreClusterNodeModel struct {
	Count     types.Int64  `tfsdk:"count"`
	Message   types.String `tfsdk:"message"`
	NodeGroup types.String `tfsdk:"node_group"`
	Nodes     types.List   `tfsdk:"nodes"`
	Role      types.String `tfsdk:"role"`
	Status    types.Bool   `tfsdk:"status"`
}

var _ basetypes.ObjectTypable = NodesType{}

type NodesType struct {
	basetypes.ObjectType
}

func (t NodesType) Equal(o attr.Type) bool {
	other, ok := o.(NodesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodesType) String() string {
	return "NodesType"
}

func (t NodesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	instanceAttribute, ok := attributes["instance"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance is missing from object`)

		return nil, diags
	}

	instanceVal, ok := instanceAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance expected to be basetypes.ObjectValue, was: %T`, instanceAttribute))
	}

	isBastionAttribute, ok := attributes["is_bastion"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_bastion is missing from object`)

		return nil, diags
	}

	isBastionVal, ok := isBastionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_bastion expected to be basetypes.BoolValue, was: %T`, isBastionAttribute))
	}

	nodeGroupIdAttribute, ok := attributes["node_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_group_id is missing from object`)

		return nil, diags
	}

	nodeGroupIdVal, ok := nodeGroupIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_group_id expected to be basetypes.Int64Value, was: %T`, nodeGroupIdAttribute))
	}

	nodeGroupNameAttribute, ok := attributes["node_group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_group_name is missing from object`)

		return nil, diags
	}

	nodeGroupNameVal, ok := nodeGroupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_group_name expected to be basetypes.StringValue, was: %T`, nodeGroupNameAttribute))
	}

	requiresPublicIpAttribute, ok := attributes["requires_public_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_public_ip is missing from object`)

		return nil, diags
	}

	requiresPublicIpVal, ok := requiresPublicIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_public_ip expected to be basetypes.BoolValue, was: %T`, requiresPublicIpAttribute))
	}

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return nil, diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	statusReasonAttribute, ok := attributes["status_reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_reason is missing from object`)

		return nil, diags
	}

	statusReasonVal, ok := statusReasonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_reason expected to be basetypes.StringValue, was: %T`, statusReasonAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodesValue{
		CreatedAt:        createdAtVal,
		Id:               idVal,
		Instance:         instanceVal,
		IsBastion:        isBastionVal,
		NodeGroupId:      nodeGroupIdVal,
		NodeGroupName:    nodeGroupNameVal,
		RequiresPublicIp: requiresPublicIpVal,
		Role:             roleVal,
		Status:           statusVal,
		StatusReason:     statusReasonVal,
		UpdatedAt:        updatedAtVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodesValueNull() NodesValue {
	return NodesValue{
		state: attr.ValueStateNull,
	}
}

func NewNodesValueUnknown() NodesValue {
	return NodesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodesValue Attribute Value",
				"While creating a NodesValue value, a missing attribute value was detected. "+
					"A NodesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodesValue Attribute Type",
				"While creating a NodesValue value, an invalid attribute value was detected. "+
					"A NodesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodesValue Attribute Value",
				"While creating a NodesValue value, an extra attribute value was detected. "+
					"A NodesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodesValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	instanceAttribute, ok := attributes["instance"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	instanceVal, ok := instanceAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance expected to be basetypes.ObjectValue, was: %T`, instanceAttribute))
	}

	isBastionAttribute, ok := attributes["is_bastion"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_bastion is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	isBastionVal, ok := isBastionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_bastion expected to be basetypes.BoolValue, was: %T`, isBastionAttribute))
	}

	nodeGroupIdAttribute, ok := attributes["node_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_group_id is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	nodeGroupIdVal, ok := nodeGroupIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_group_id expected to be basetypes.Int64Value, was: %T`, nodeGroupIdAttribute))
	}

	nodeGroupNameAttribute, ok := attributes["node_group_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`node_group_name is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	nodeGroupNameVal, ok := nodeGroupNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`node_group_name expected to be basetypes.StringValue, was: %T`, nodeGroupNameAttribute))
	}

	requiresPublicIpAttribute, ok := attributes["requires_public_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_public_ip is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	requiresPublicIpVal, ok := requiresPublicIpAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_public_ip expected to be basetypes.BoolValue, was: %T`, requiresPublicIpAttribute))
	}

	roleAttribute, ok := attributes["role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`role is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	roleVal, ok := roleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`role expected to be basetypes.StringValue, was: %T`, roleAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	statusReasonAttribute, ok := attributes["status_reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_reason is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	statusReasonVal, ok := statusReasonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_reason expected to be basetypes.StringValue, was: %T`, statusReasonAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewNodesValueUnknown(), diags
	}

	return NodesValue{
		CreatedAt:        createdAtVal,
		Id:               idVal,
		Instance:         instanceVal,
		IsBastion:        isBastionVal,
		NodeGroupId:      nodeGroupIdVal,
		NodeGroupName:    nodeGroupNameVal,
		RequiresPublicIp: requiresPublicIpVal,
		Role:             roleVal,
		Status:           statusVal,
		StatusReason:     statusReasonVal,
		UpdatedAt:        updatedAtVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewNodesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodesValue {
	object, diags := NewNodesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodesValueMust(NodesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodesType) ValueType(ctx context.Context) attr.Value {
	return NodesValue{}
}

var _ basetypes.ObjectValuable = NodesValue{}

type NodesValue struct {
	CreatedAt        basetypes.StringValue `tfsdk:"created_at"`
	Id               basetypes.Int64Value  `tfsdk:"id"`
	Instance         basetypes.ObjectValue `tfsdk:"instance"`
	IsBastion        basetypes.BoolValue   `tfsdk:"is_bastion"`
	NodeGroupId      basetypes.Int64Value  `tfsdk:"node_group_id"`
	NodeGroupName    basetypes.StringValue `tfsdk:"node_group_name"`
	RequiresPublicIp basetypes.BoolValue   `tfsdk:"requires_public_ip"`
	Role             basetypes.StringValue `tfsdk:"role"`
	Status           basetypes.StringValue `tfsdk:"status"`
	StatusReason     basetypes.StringValue `tfsdk:"status_reason"`
	UpdatedAt        basetypes.StringValue `tfsdk:"updated_at"`
	state            attr.ValueState
}

func (v NodesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["instance"] = basetypes.ObjectType{
		AttrTypes: InstanceValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["is_bastion"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["node_group_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["node_group_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["requires_public_ip"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["role"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status_reason"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Instance.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["instance"] = val

		val, err = v.IsBastion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_bastion"] = val

		val, err = v.NodeGroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["node_group_id"] = val

		val, err = v.NodeGroupName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["node_group_name"] = val

		val, err = v.RequiresPublicIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["requires_public_ip"] = val

		val, err = v.Role.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["role"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.StatusReason.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status_reason"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodesValue) String() string {
	return "NodesValue"
}

func (v NodesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var instance basetypes.ObjectValue

	if v.Instance.IsNull() {
		instance = types.ObjectNull(
			InstanceValue{}.AttributeTypes(ctx),
		)
	}

	if v.Instance.IsUnknown() {
		instance = types.ObjectUnknown(
			InstanceValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Instance.IsNull() && !v.Instance.IsUnknown() {
		instance = types.ObjectValueMust(
			InstanceValue{}.AttributeTypes(ctx),
			v.Instance.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"created_at": basetypes.StringType{},
		"id":         basetypes.Int64Type{},
		"instance": basetypes.ObjectType{
			AttrTypes: InstanceValue{}.AttributeTypes(ctx),
		},
		"is_bastion":         basetypes.BoolType{},
		"node_group_id":      basetypes.Int64Type{},
		"node_group_name":    basetypes.StringType{},
		"requires_public_ip": basetypes.BoolType{},
		"role":               basetypes.StringType{},
		"status":             basetypes.StringType{},
		"status_reason":      basetypes.StringType{},
		"updated_at":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":         v.CreatedAt,
			"id":                 v.Id,
			"instance":           instance,
			"is_bastion":         v.IsBastion,
			"node_group_id":      v.NodeGroupId,
			"node_group_name":    v.NodeGroupName,
			"requires_public_ip": v.RequiresPublicIp,
			"role":               v.Role,
			"status":             v.Status,
			"status_reason":      v.StatusReason,
			"updated_at":         v.UpdatedAt,
		})

	return objVal, diags
}

func (v NodesValue) Equal(o attr.Value) bool {
	other, ok := o.(NodesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Instance.Equal(other.Instance) {
		return false
	}

	if !v.IsBastion.Equal(other.IsBastion) {
		return false
	}

	if !v.NodeGroupId.Equal(other.NodeGroupId) {
		return false
	}

	if !v.NodeGroupName.Equal(other.NodeGroupName) {
		return false
	}

	if !v.RequiresPublicIp.Equal(other.RequiresPublicIp) {
		return false
	}

	if !v.Role.Equal(other.Role) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.StatusReason.Equal(other.StatusReason) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v NodesValue) Type(ctx context.Context) attr.Type {
	return NodesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at": basetypes.StringType{},
		"id":         basetypes.Int64Type{},
		"instance": basetypes.ObjectType{
			AttrTypes: InstanceValue{}.AttributeTypes(ctx),
		},
		"is_bastion":         basetypes.BoolType{},
		"node_group_id":      basetypes.Int64Type{},
		"node_group_name":    basetypes.StringType{},
		"requires_public_ip": basetypes.BoolType{},
		"role":               basetypes.StringType{},
		"status":             basetypes.StringType{},
		"status_reason":      basetypes.StringType{},
		"updated_at":         basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = InstanceType{}

type InstanceType struct {
	basetypes.ObjectType
}

func (t InstanceType) Equal(o attr.Type) bool {
	other, ok := o.(InstanceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t InstanceType) String() string {
	return "InstanceType"
}

func (t InstanceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	contractIdAttribute, ok := attributes["contract_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`contract_id is missing from object`)

		return nil, diags
	}

	contractIdVal, ok := contractIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`contract_id expected to be basetypes.Int64Value, was: %T`, contractIdAttribute))
	}

	fixedIpAttribute, ok := attributes["fixed_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ip is missing from object`)

		return nil, diags
	}

	fixedIpVal, ok := fixedIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ip expected to be basetypes.StringValue, was: %T`, fixedIpAttribute))
	}

	floatingIpAttribute, ok := attributes["floating_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`floating_ip is missing from object`)

		return nil, diags
	}

	floatingIpVal, ok := floatingIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`floating_ip expected to be basetypes.StringValue, was: %T`, floatingIpAttribute))
	}

	floatingIpStatusAttribute, ok := attributes["floating_ip_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`floating_ip_status is missing from object`)

		return nil, diags
	}

	floatingIpStatusVal, ok := floatingIpStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`floating_ip_status expected to be basetypes.StringValue, was: %T`, floatingIpStatusAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	imageIdAttribute, ok := attributes["image_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_id is missing from object`)

		return nil, diags
	}

	imageIdVal, ok := imageIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_id expected to be basetypes.Int64Value, was: %T`, imageIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return InstanceValue{
		ContractId:       contractIdVal,
		FixedIp:          fixedIpVal,
		FloatingIp:       floatingIpVal,
		FloatingIpStatus: floatingIpStatusVal,
		Id:               idVal,
		ImageId:          imageIdVal,
		Name:             nameVal,
		Status:           statusVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewInstanceValueNull() InstanceValue {
	return InstanceValue{
		state: attr.ValueStateNull,
	}
}

func NewInstanceValueUnknown() InstanceValue {
	return InstanceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewInstanceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (InstanceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing InstanceValue Attribute Value",
				"While creating a InstanceValue value, a missing attribute value was detected. "+
					"A InstanceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid InstanceValue Attribute Type",
				"While creating a InstanceValue value, an invalid attribute value was detected. "+
					"A InstanceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra InstanceValue Attribute Value",
				"While creating a InstanceValue value, an extra attribute value was detected. "+
					"A InstanceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra InstanceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewInstanceValueUnknown(), diags
	}

	contractIdAttribute, ok := attributes["contract_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`contract_id is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	contractIdVal, ok := contractIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`contract_id expected to be basetypes.Int64Value, was: %T`, contractIdAttribute))
	}

	fixedIpAttribute, ok := attributes["fixed_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fixed_ip is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	fixedIpVal, ok := fixedIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fixed_ip expected to be basetypes.StringValue, was: %T`, fixedIpAttribute))
	}

	floatingIpAttribute, ok := attributes["floating_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`floating_ip is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	floatingIpVal, ok := floatingIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`floating_ip expected to be basetypes.StringValue, was: %T`, floatingIpAttribute))
	}

	floatingIpStatusAttribute, ok := attributes["floating_ip_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`floating_ip_status is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	floatingIpStatusVal, ok := floatingIpStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`floating_ip_status expected to be basetypes.StringValue, was: %T`, floatingIpStatusAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	imageIdAttribute, ok := attributes["image_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_id is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	imageIdVal, ok := imageIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_id expected to be basetypes.Int64Value, was: %T`, imageIdAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewInstanceValueUnknown(), diags
	}

	return InstanceValue{
		ContractId:       contractIdVal,
		FixedIp:          fixedIpVal,
		FloatingIp:       floatingIpVal,
		FloatingIpStatus: floatingIpStatusVal,
		Id:               idVal,
		ImageId:          imageIdVal,
		Name:             nameVal,
		Status:           statusVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewInstanceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) InstanceValue {
	object, diags := NewInstanceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewInstanceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t InstanceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewInstanceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewInstanceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewInstanceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewInstanceValueMust(InstanceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t InstanceType) ValueType(ctx context.Context) attr.Value {
	return InstanceValue{}
}

var _ basetypes.ObjectValuable = InstanceValue{}

type InstanceValue struct {
	ContractId       basetypes.Int64Value  `tfsdk:"contract_id"`
	FixedIp          basetypes.StringValue `tfsdk:"fixed_ip"`
	FloatingIp       basetypes.StringValue `tfsdk:"floating_ip"`
	FloatingIpStatus basetypes.StringValue `tfsdk:"floating_ip_status"`
	Id               basetypes.Int64Value  `tfsdk:"id"`
	ImageId          basetypes.Int64Value  `tfsdk:"image_id"`
	Name             basetypes.StringValue `tfsdk:"name"`
	Status           basetypes.StringValue `tfsdk:"status"`
	state            attr.ValueState
}

func (v InstanceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["contract_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["fixed_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["floating_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["floating_ip_status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["image_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.ContractId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["contract_id"] = val

		val, err = v.FixedIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fixed_ip"] = val

		val, err = v.FloatingIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["floating_ip"] = val

		val, err = v.FloatingIpStatus.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["floating_ip_status"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.ImageId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["image_id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v InstanceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v InstanceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v InstanceValue) String() string {
	return "InstanceValue"
}

func (v InstanceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"contract_id":        basetypes.Int64Type{},
		"fixed_ip":           basetypes.StringType{},
		"floating_ip":        basetypes.StringType{},
		"floating_ip_status": basetypes.StringType{},
		"id":                 basetypes.Int64Type{},
		"image_id":           basetypes.Int64Type{},
		"name":               basetypes.StringType{},
		"status":             basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"contract_id":        v.ContractId,
			"fixed_ip":           v.FixedIp,
			"floating_ip":        v.FloatingIp,
			"floating_ip_status": v.FloatingIpStatus,
			"id":                 v.Id,
			"image_id":           v.ImageId,
			"name":               v.Name,
			"status":             v.Status,
		})

	return objVal, diags
}

func (v InstanceValue) Equal(o attr.Value) bool {
	other, ok := o.(InstanceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ContractId.Equal(other.ContractId) {
		return false
	}

	if !v.FixedIp.Equal(other.FixedIp) {
		return false
	}

	if !v.FloatingIp.Equal(other.FloatingIp) {
		return false
	}

	if !v.FloatingIpStatus.Equal(other.FloatingIpStatus) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.ImageId.Equal(other.ImageId) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v InstanceValue) Type(ctx context.Context) attr.Type {
	return InstanceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v InstanceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"contract_id":        basetypes.Int64Type{},
		"fixed_ip":           basetypes.StringType{},
		"floating_ip":        basetypes.StringType{},
		"floating_ip_status": basetypes.StringType{},
		"id":                 basetypes.Int64Type{},
		"image_id":           basetypes.Int64Type{},
		"name":               basetypes.StringType{},
		"status":             basetypes.StringType{},
	}
}
